name: CI/CD counter app

on:
  push:
    branches:
      - main

jobs:
#First we will see the application build or not , then we will deploy in EC2
  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v2
    
  #   - name: Build the docker_compose
  #     run: docker build -t counter-service .
      
  #   - name: Run the application
  #     run: docker run -d -p 80:80 counter-service

  Deploy:
    # needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY  }}
          REMOTE_HOST : ${{ secrets.HOST_DNS  }}
          REMOTE_USER : ${{ secrets.USERNAME  }}
            
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_HOST} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            mkdir /home/centos/CounterApp
            sudo yum install git -y
            sudo yum install -y yum-utils
            sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
            sudo yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            sudo systemctl start docker
            cd /home/centos/CounterApp &&
            sudo git clone  https://github.com/MaximMandelblum/payoneer.git
            sudo docker build -t counter-service .
            sudo docker run -d -p 80:80 counter-service '