name: Deploy to EC2

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies and build the app
        run: |

          mkdir /home/centos/payoneer
          # npm run build

      - name: Deploy to EC2
        run: |
          # Replace 'USERNAME', 'EC2_PUBLIC_IP', and '/path/to/your/app' with your actual values
          ssh -o StrictHostKeyChecking=no centos@3.71.38.22 "cd /home/centos/payoneer"